// Exception Handling

// const x = parseInt(prompt("Enter the value of x"))
// const y = parseInt(prompt("Enter the value of y"))

// let ans;
//     if(y === 0){
//         throw new Error("Divide by zero is not possible.")
//     }

//     ans = x / y

//     console.log(ans)

//     let name = "amit"
//     console.log(name)

// try {
//     let ans;
//     if(y === 0){
//         throw new Error("Divide by zero is not possible.")
//     }

//     ans = x / y

//     console.log(ans)
// } catch (error) {
//     console.log(error.message)
// } finally {
//     console.log("run in every case");
// }